"""empty message

Revision ID: 0a6f630786fa
Revises: 801fe3d06dfc
Create Date: 2025-07-09 10:27:18.004565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6f630786fa'
down_revision = '801fe3d06dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_character_fav',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('user_planet_fav',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('race', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('native_planet', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('is_jedi', sa.Boolean(), nullable=False))

    with op.batch_alter_table('fav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_owner', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('caption', sa.String(length=240), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('solar_system', sa.String(length=60), nullable=False))

    with op.batch_alter_table('weapon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_lethal', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('weapon_owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'character', ['weapon_owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('weapon_owner_id')
        batch_op.drop_column('is_lethal')
        batch_op.drop_column('name')
        batch_op.drop_column('type')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('solar_system')
        batch_op.drop_column('name')

    with op.batch_alter_table('fav', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('caption')
        batch_op.drop_column('post_owner')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('is_jedi')
        batch_op.drop_column('native_planet')
        batch_op.drop_column('race')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.drop_table('user_planet_fav')
    op.drop_table('user_character_fav')
    # ### end Alembic commands ###
